### ISSUE TITLE
Disproportionation tree badly formed?

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-database#158]
One of the head nodes in the disproporationation family is `Y_rad_birad_trirad_quadrad`, defined as a logic node, `OR{Y_1centerquadrad, Y_1centertrirad, Y_2centerbirad, Y_1centerbirad, Y_rad, H_rad}`.

Y_rad is defined as `R u1`, and H_rad is defined as `H u1`, so they are not mutually exclusive. This leads to any disprop reaction involving an H radical having twice the expected degeneracy.

I wanted to ask and confirm that this is not intentional, and that Y_rad should be changed to be `R!H u1`.

**Comment by nyee** [comment]
In the tree `H_rad` is L3 level with parent as `Y_rad.` I think its a mistake in the definition of `Y_rad_birad_trirad_quadrad`: it should not have `H_rad`. Could be a mistake from sloppy (probably my) tree-reordering. 

Either way as a very small amount of optimization, I would recommend moving `H_rad` higher in the tree because it is probably the most commonly hit radical.

**Comment by mliu49** [comment]
Ah, good point. I didn't look at the tree. I'll make a PR.
