### ISSUE TITLE
Non-Python 3 related issues with scripts

### ISSUE THREAD

**Issue by ajocher** [ReactionMechanismGenerator/RMG-database#363]
Transitioning kineticsGroups.py and kineticsTraining.py scripts to Python 3 brought up several non-Python 3 related issues. 
Are these two scripts still actively used and are they still useful or could they be deleted?

**Comment by mjohnson541** [comment]
I've never used either of those scripts or heard of anyone using them, kineticsTraining.py in particular looks difficult to use.  @mliu49 do you know anything about the history of these scripts?

**Comment by mliu49** [comment]
I don't know much about those scripts either, which is why I suggested that @ajocher create an issue about it. kineticsGroups.py is related to working with kinetics group additivity and kineticsTraining.py is for creating rules from sets of training data. It seems to me like they are no longer necessary.

**Comment by mjohnson541** [comment]
I'm in favor of deprecating them.

**Comment by ajocher** [comment]
OK, I agree.
