### ISSUE TITLE
"source activate rmg_env" stopped working -- on new macOS?

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-database#370]
When I run "source activate rmg_env" on my MacBook Pro (2019) running macOS 10.15.2 Catalina, I'm getting:
/Users/mcninch/anaconda2/envs/rmg_env/etc/conda/activate.d/keras_activate.sh:2: = not found

My rmg ran fine before the OS update. I checked the entire path and it's fine, giving the shell script:

### **#!/bin/bash
if [ "$(uname)" == "Darwin" ]
then
    # for Mac OSX
    export KERAS_BACKEND=tensorflow
elif [ "$(uname)" == "Linux" ]
then
    # for Linux
    export KERAS_BACKEND=theano
fi**

Ideas???

**Comment by alongd** [comment]
Try `conda activate rmg_env` instead

**Comment by PWstmrlnd** [comment]
No, still got:
/Users/mcninch/anaconda2/envs/rmg_env/etc/conda/activate.d/keras_activate.sh:2: = not found

**Comment by mliu49** [comment]
This was also reported in keras-team/keras#9029 in January of 2018, with no responses. According to [this StackOverflow comment](https://stackoverflow.com/questions/43327464/how-to-make-keras-use-tensorflow-backend-in-anaconda/43328647#43328647), this script is part of how conda-forge packages keras. A similar error is reported in conda-forge/toolchain-feedstock#49, which points towards this being an issue with zsh, which became the default shell in MacOS Catalina.

If you prefer using zsh, there are some comments in the conda-forge issue about how to fix this error. Otherwise, I would suggest setting your default shell back to bash: [How to change default shell in MacOS](https://www.howtogeek.com/444596/how-to-change-the-default-shell-to-bash-in-macos-catalina/).

**Comment by PWstmrlnd** [comment]
Yes! I reset to bash, and now the calculation is chugging along. Thank you.
