### ISSUE TITLE
Forbidden structure issue after making Intra_R_Add_Exocyclic ATG

### ISSUE THREAD

**Issue by xiaoruiDong** [ReactionMechanismGenerator/RMG-database#577]
The following reaction generation faces an issue after converting the Intra_R_Add_Exocyclic family into an ATG tree.

```
database.kinetics.generate_reactions(reactants=[Molecule().from_smiles('C1=C[CH]C=CC=1')],
                                     products=[Molecule().from_smiles('[CH]1C2=CC=CC12')],
                                     resonance=True)
```
Returns with a reaction from this family, with template = `'Root_Ext-3R!H-R_Ext-4R!H-R_N-Sp-5R!H#4R!H_4R!H-inRing'`, however, if we reverse the sequence of the reactant and the product, 
```
database.kinetics.generate_reactions(reactants=[Molecule().from_smiles('[CH]1C2=CC=CC12')],
                                     products=[Molecule().from_smiles('C1=C[CH]C=CC=1')],
                                     resonance=True)
```
It will raise an error of
```
UndeterminableKineticsError: (TemplateReaction(reactants=[Molecule(smiles="C1=C[CH]C=CC=1")], products=[Molecule(smiles="[CH]1C2=CC=CC12")], pairs=[[Molecule(smiles="C1=C[CH]C=CC=1"), Molecule(smiles="[CH]1C2=CC=CC12")]], family='Intra_R_Add_Exocyclic'), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "C1=C[CH]C=CC=1"> <=> <Molecule "[CH]1C2=CC=CC12"> in reaction family <KineticsGroups "Intra_R_Add_Exocyclic/groups">.Trying to match [<Entry index=0 label="Root">] but matched []')
``` 

The issue is that the reactant has a substructure that is forbidden. 

```
forbidden(
    label = "cyclic_1",
    group = 
"""
1 *2 R!H u0 r1 {2,[D,T,B]} {3,[S,D,T,B]}
2 *3 R!H u0 r1 {1,[D,T,B]}
3 *1 R!H u1 r1 {1,[S,D,T,B]}
""",
    shortDesc = """""",
    longDesc = 
"""
Intra addition to double bond in ring should occur in Intra_R_Add_Endocyclic.
""",
)
```

Question 1: For cases like this, does it mean we may need to forbid its product structure? I personally find it is not easy to do, e.g., the following will mistakenly forbid other reactions. It may be more desirable to define that atoms 1, 2, and 3 are in the same ring, but I don't think there is an easy way to do it.
```
"""
1 *2 R!H u0 r1 {2,[D,T,B]} {3,[S,D,T,B]}
2 *3 R!H u1 r1 {1,[D,T,B]}
3 *1 R!H u0 r1 {1,[S,D,T,B]}
""",
```
Question 2: Should we simply neglect a reaction if either reactant or product matches a forbidden structure after labeling atoms in the reaction center? Is this something already implemented in the RMG but fails here, or do we have any concerns about implementing this?

**Comment by hwpang** [comment]
@xiaoruiDong I was thinking about this issue too. 

I think the underlying problem is that the ATG root node for `Intra_R_Add_Endocyclic` and `Intra_R_Add_Exocyclic` are the same. They both only define a radical reacting site and a double bond reacting site, and no further restriction on the endocyclic or the exocyclic part. To my understanding, for the old tree, the template was defined such that it took care of most of the endocyclic/exocyclic differences, and the forbidden group is used to prevent some edge cases. But now with the root node being the same, this forbidden groups are forced to be comprehensive, which is difficult to define because it needs to consider all the possible backbone.

Taking a closer look at this specific reaction, I notice that back in commit `89564b633c85066419c6f66f9420ecf5e4b94b30`, this reaction is not generated in either `Intra_R_Add_Endocyclic` or `Intra_R_Add_Exocyclic`. After that commit, this reaction is generated for both direction in `Intra_R_Add_Endocyclic` and only one direction in `Intra_R_Add_Exocyclic`. In other words, the new tree somehow introduces a subset of reactions that weren't allowed in the old tree.

I think there are several things we should consider

1. Does it still make sense to keep these two families separated? Could we merge the families and let ATG to decide if their rate is that much different? If we decide to keep them separated, I think we should somehow make ATG tell these two families apart
2. Should we narrow the root node or add additional forbidden groups to somehow to prevent this reaction to be introduced in the first place?

**Comment by hwpang** [comment]
And this reaction is ambiguous in terms of endocyclic/exocyclic? If you consider the 5 carbon ring part, it is exocyclic, but for the 3 carbon ring part, it is endocyclic. So it's not really the case cyclic_1 tries to forbide. 

![image](https://user-images.githubusercontent.com/45482070/165672108-f1ae2a2f-c538-49a9-ad80-94c75e2b804d.png)

**Comment by hwpang** [comment]
This issue should be fixed by https://github.com/ReactionMechanismGenerator/RMG-database/pull/583. After that PR was merged, the RMG-tests can without errors (e.g. https://github.com/ReactionMechanismGenerator/RMG-tests/actions/runs/2332569355). I will close this issue for now.
